version: '3'

services:
  postgres-db-pgadmin:
    image: dpage/pgadmin4
    hostname: postgres-pgadmin
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8080:80
    networks:
      - backend_network

  postgres-db:
    image: postgres
    hostname: postgres-db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/dbdata
    ports:
      - 5433:5432
    networks:
      - backend_network

networks:
  backend_network:
    external: true