version: '3'

services: 
  oracle-db:
    image: oracleinanutshell/oracle-xe-11g:latest
    hostname: oracle-db
    ports:
      - 1521:1521
      - 5500:5500
    networks:
      - backend_network

networks:
  backend_network:
    external: true